version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laps-app
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV:-production}
      - HTTP_PORT=${HTTP_PORT:-8080}
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-laps}
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE:-disable}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "${HTTP_PORT:-8080}:8080"
    # networks:
    #   - laps-network
    volumes:
      - ./logs:/app/logs
