version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laps-app
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV:-production}
      - HTTP_PORT=${HTTP_PORT:-8080}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-laps}
      - POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE:-disable}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - S3_ENDPOINT=${S3_ENDPOINT:-s3.amazonaws.com}
      - S3_REGION=${S3_REGION:-eu-north-1}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET:-lapsbucket2302}
      - S3_USE_SSL=${S3_USE_SSL:-true}
    ports:
      - "${HTTP_PORT:-8080}:8080"
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:14-alpine
    container_name: laps-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-laps}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
