ALTER TABLE work_experience
ADD COLUMN IF NOT EXISTS from_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS to_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE education 
ADD COLUMN IF NOT EXISTS field_of_study VARCHAR(255),
ADD COLUMN IF NOT EXISTS from_year INT,
ADD COLUMN IF NOT EXISTS to_year INT; 