name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up environment file
      run: |
        cat > .env << EOF
        HTTP_PORT=8080
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_SSL_MODE=disable
        JWT_SIGNING_KEY=${{ secrets.JWT_SIGNING_KEY }}
        LOG_LEVEL=info
        EOF
        
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "go.mod, go.sum, docker-compose.yml, Dockerfile, ./internal, ./cmd, ./pkg, ./migrations, ./configs"
        target: "/home/${{ secrets.SERVER_USER }}/laps-app"
        
    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SERVER_USER }}/laps-app
          sudo docker-compose build
          sudo docker-compose down
          sudo docker-compose up -d
          
          sleep 10
          
          sudodocker-compose exec app ./laps migrate