name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: laps-api:latest
        
    - name: Save Docker image
      run: docker save laps-api:latest > laps-api.tar
      
    - name: Set up environment file
      run: |
        cat > .env << EOF
        HTTP_PORT=8080
        POSTGRES_USER=${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB=${{ secrets.POSTGRES_DB }}
        POSTGRES_SSL_MODE=disable
        JWT_SIGNING_KEY=${{ secrets.JWT_SIGNING_KEY }}
        LOG_LEVEL=info
        EOF
        
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "laps-api.tar,.env"
        target: "/home/${{ secrets.SERVER_USER }}/laps-app"
        
    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SERVER_USER }}/laps-app\
          sudo docker load < laps-api.tar
          
          source .env
          sudo docker stop laps-api || true
          sudo docker rm laps-api || true
          sudo docker run -d \
            --name laps-api \
            --restart unless-stopped \
            -p "${HTTP_PORT:-8080}:8080" \
            -e POSTGRES_HOST=host.docker.internal \
            -e POSTGRES_PORT=5432 \
            -e POSTGRES_USER="${POSTGRES_USER}" \
            -e POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
            -e POSTGRES_DB="${POSTGRES_DB:-laps}" \
            -e POSTGRES_SSL_MODE=disable \
            -e JWT_SIGNING_KEY="${JWT_SIGNING_KEY}" \
            -e LOG_LEVEL=info \
            --add-host=host.docker.internal:host-gateway \
            laps-api:latest
          
          sleep 10
          sudo docker exec laps-api ./laps migrate || echo "Миграции не выполнены"